/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SvgsRouteImport } from './routes/svgs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectSlugRouteImport } from './routes/$projectSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as ProjectSlugIndexRouteImport } from './routes/$projectSlug/index'
import { Route as OnboardingSuccessRouteImport } from './routes/onboarding/success'
import { Route as ProjectSlugServiceSlugRouteImport } from './routes/$projectSlug/$serviceSlug'
import { Route as ProjectSlugServiceSlugIndexRouteImport } from './routes/$projectSlug/$serviceSlug/index'
import { Route as ProjectSlugServiceSlugServiceTabRouteImport } from './routes/$projectSlug/$serviceSlug/$serviceTab'

const SvgsRoute = SvgsRouteImport.update({
  id: '/svgs',
  path: '/svgs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/$projectSlug',
  path: '/$projectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugIndexRoute = ProjectSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const OnboardingSuccessRoute = OnboardingSuccessRouteImport.update({
  id: '/onboarding/success',
  path: '/onboarding/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugServiceSlugRoute = ProjectSlugServiceSlugRouteImport.update({
  id: '/$serviceSlug',
  path: '/$serviceSlug',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugServiceSlugIndexRoute =
  ProjectSlugServiceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectSlugServiceSlugRoute,
  } as any)
const ProjectSlugServiceSlugServiceTabRoute =
  ProjectSlugServiceSlugServiceTabRouteImport.update({
    id: '/$serviceTab',
    path: '/$serviceTab',
    getParentRoute: () => ProjectSlugServiceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectSlug': typeof ProjectSlugRouteWithChildren
  '/login': typeof LoginRoute
  '/svgs': typeof SvgsRoute
  '/$projectSlug/$serviceSlug': typeof ProjectSlugServiceSlugRouteWithChildren
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/$projectSlug/': typeof ProjectSlugIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/$projectSlug/$serviceSlug/$serviceTab': typeof ProjectSlugServiceSlugServiceTabRoute
  '/$projectSlug/$serviceSlug/': typeof ProjectSlugServiceSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/svgs': typeof SvgsRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/$projectSlug': typeof ProjectSlugIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/$projectSlug/$serviceSlug/$serviceTab': typeof ProjectSlugServiceSlugServiceTabRoute
  '/$projectSlug/$serviceSlug': typeof ProjectSlugServiceSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectSlug': typeof ProjectSlugRouteWithChildren
  '/login': typeof LoginRoute
  '/svgs': typeof SvgsRoute
  '/$projectSlug/$serviceSlug': typeof ProjectSlugServiceSlugRouteWithChildren
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/$projectSlug/': typeof ProjectSlugIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/$projectSlug/$serviceSlug/$serviceTab': typeof ProjectSlugServiceSlugServiceTabRoute
  '/$projectSlug/$serviceSlug/': typeof ProjectSlugServiceSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$projectSlug'
    | '/login'
    | '/svgs'
    | '/$projectSlug/$serviceSlug'
    | '/onboarding/success'
    | '/$projectSlug/'
    | '/onboarding/'
    | '/$projectSlug/$serviceSlug/$serviceTab'
    | '/$projectSlug/$serviceSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/svgs'
    | '/onboarding/success'
    | '/$projectSlug'
    | '/onboarding'
    | '/$projectSlug/$serviceSlug/$serviceTab'
    | '/$projectSlug/$serviceSlug'
  id:
    | '__root__'
    | '/'
    | '/$projectSlug'
    | '/login'
    | '/svgs'
    | '/$projectSlug/$serviceSlug'
    | '/onboarding/success'
    | '/$projectSlug/'
    | '/onboarding/'
    | '/$projectSlug/$serviceSlug/$serviceTab'
    | '/$projectSlug/$serviceSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectSlugRoute: typeof ProjectSlugRouteWithChildren
  LoginRoute: typeof LoginRoute
  SvgsRoute: typeof SvgsRoute
  OnboardingSuccessRoute: typeof OnboardingSuccessRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/svgs': {
      id: '/svgs'
      path: '/svgs'
      fullPath: '/svgs'
      preLoaderRoute: typeof SvgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug': {
      id: '/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/$projectSlug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/': {
      id: '/$projectSlug/'
      path: '/'
      fullPath: '/$projectSlug/'
      preLoaderRoute: typeof ProjectSlugIndexRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/onboarding/success': {
      id: '/onboarding/success'
      path: '/onboarding/success'
      fullPath: '/onboarding/success'
      preLoaderRoute: typeof OnboardingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/$serviceSlug': {
      id: '/$projectSlug/$serviceSlug'
      path: '/$serviceSlug'
      fullPath: '/$projectSlug/$serviceSlug'
      preLoaderRoute: typeof ProjectSlugServiceSlugRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/$projectSlug/$serviceSlug/': {
      id: '/$projectSlug/$serviceSlug/'
      path: '/'
      fullPath: '/$projectSlug/$serviceSlug/'
      preLoaderRoute: typeof ProjectSlugServiceSlugIndexRouteImport
      parentRoute: typeof ProjectSlugServiceSlugRoute
    }
    '/$projectSlug/$serviceSlug/$serviceTab': {
      id: '/$projectSlug/$serviceSlug/$serviceTab'
      path: '/$serviceTab'
      fullPath: '/$projectSlug/$serviceSlug/$serviceTab'
      preLoaderRoute: typeof ProjectSlugServiceSlugServiceTabRouteImport
      parentRoute: typeof ProjectSlugServiceSlugRoute
    }
  }
}

interface ProjectSlugServiceSlugRouteChildren {
  ProjectSlugServiceSlugServiceTabRoute: typeof ProjectSlugServiceSlugServiceTabRoute
  ProjectSlugServiceSlugIndexRoute: typeof ProjectSlugServiceSlugIndexRoute
}

const ProjectSlugServiceSlugRouteChildren: ProjectSlugServiceSlugRouteChildren =
  {
    ProjectSlugServiceSlugServiceTabRoute:
      ProjectSlugServiceSlugServiceTabRoute,
    ProjectSlugServiceSlugIndexRoute: ProjectSlugServiceSlugIndexRoute,
  }

const ProjectSlugServiceSlugRouteWithChildren =
  ProjectSlugServiceSlugRoute._addFileChildren(
    ProjectSlugServiceSlugRouteChildren,
  )

interface ProjectSlugRouteChildren {
  ProjectSlugServiceSlugRoute: typeof ProjectSlugServiceSlugRouteWithChildren
  ProjectSlugIndexRoute: typeof ProjectSlugIndexRoute
}

const ProjectSlugRouteChildren: ProjectSlugRouteChildren = {
  ProjectSlugServiceSlugRoute: ProjectSlugServiceSlugRouteWithChildren,
  ProjectSlugIndexRoute: ProjectSlugIndexRoute,
}

const ProjectSlugRouteWithChildren = ProjectSlugRoute._addFileChildren(
  ProjectSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectSlugRoute: ProjectSlugRouteWithChildren,
  LoginRoute: LoginRoute,
  SvgsRoute: SvgsRoute,
  OnboardingSuccessRoute: OnboardingSuccessRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
